### ISSUE TITLE
Can't use API key?

### ISSUE THREAD

**Issue by tiredcisadmin** [DipFlip/markdown-to-confluence#1]
I saw in your comment on the markdown-confluence [issue 91](https://github.com/markdown-confluence/markdown-confluence/issues/91#issuecomment-2399316554) that you said you had to use UN/PW. My org uses SSO, so that won't work for me. Why did the API key not work?

**Comment by DipFlip** [comment]
I'm afraid I don't remember now and it might very well be that I didn't configure the API key call correctly. When I switched to the current username, password authentication it worked for my use case.

**Comment by tiredcisadmin** [comment]
Thanks for the response!
